name: darkevil_game
description: A 2D side-scrolling adventure game built with Flame.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flame: ^1.15.0
  flame_audio: ^1.3.3
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/hero.png
    - assets/enemies.png
    - assets/boss.png
    - assets/bg.png
    - assets/intro_scene.png
    - assets/logo.png
