name: darkevil_game
description: A retro side-scrolling adventure game made with Flutter & Flame.
publish_to: "none" # private project

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.13.1
  flutter_lints: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/hero.png
    - assets/enemies.png
    - assets/boss.png
    - assets/bg.png
    - assets/intro_scene.png
    - assets/logo.png

  # Uncomment if you want custom fonts
  # fonts:
  #   - family: GameFont
  #     fonts:
  #       - asset: assets/fonts/game_font.ttf
