name: darkevil_game
description: A 2D side-scrolling adventure game built with Flame.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Game engine
  flame: ^1.23.0
  flame_audio: ^2.11.10

  # Fonts
  google_fonts: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/hero.png
    - assets/enemies.png
    - assets/boss.png
    - assets/bg.png
    - assets/intro_scene.png
    - assets/logo.png
