name: Flutter Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.24.0'

      - name: Ensure Android folder (v2 embedding)
        run: |
          if [ ! -d "android" ]; then
            flutter create .
          fi

      - name: Install dependencies
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: darkevil_game-apk
          path: build/app/outputs/flutter-apk/app-release.apk
